// Authentication action types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Task fetching & CRUD action types
export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST"; // Fixed typo here
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

// Filters & search
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_PRIORITY_FILTER = "SET_PRIORITY_FILTER";
export const SET_STATUS_FILTER = "SET_STATUS_FILTER";
export const SET_DUE_DATE_FILTER = "SET_DUE_DATE_FILTER";

// Assign tasks (for task requests/assigning system)
export const ASSIGN_TASK_REQUEST = "ASSIGN_TASK_REQUEST";
export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS";
export const ASSIGN_TASK_FAILURE = "ASSIGN_TASK_FAILURE";

export const GET_ASSIGNED_TASKS_REQUEST = "GET_ASSIGNED_TASKS_REQUEST";
export const GET_ASSIGNED_TASKS_SUCCESS = "GET_ASSIGNED_TASKS_SUCCESS";
export const GET_ASSIGNED_TASKS_FAILURE = "GET_ASSIGNED_TASKS_FAILURE";

// Real-time task request events & updates
export const NEW_ASSIGN_TASK_RECEIVED = "NEW_ASSIGN_TASK_RECEIVED";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";
export const RESPOND_TO_TASK_REQUEST = "RESPOND_TO_TASK_REQUEST";

export const INCREMENT_REQUEST_COUNT = "INCREMENT_REQUEST_COUNT";
export const DECREMENT_REQUEST_COUNT = "DECREMENT_REQUEST_COUNT";

// Editing assigned tasks
export const TASK_ASSIGNED = "TASK_ASSIGNED";
export const EDIT_ASSIGNED_TASK_REQUEST = "EDIT_ASSIGNED_TASK_REQUEST";
export const EDIT_ASSIGNED_TASK_SUCCESS = "EDIT_ASSIGNED_TASK_SUCCESS";
export const EDIT_ASSIGNED_TASK_FAILURE = "EDIT_ASSIGNED_TASK_FAILURE";

// Deleting assigned tasks
export const DELETE_ASSIGNED_TASK_REQUEST = "DELETE_ASSIGNED_TASK_REQUEST";
export const DELETE_ASSIGNED_TASK_SUCCESS = "DELETE_ASSIGNED_TASK_SUCCESS";
export const DELETE_ASSIGNED_TASK_FAILURE = "DELETE_ASSIGNED_TASK_FAILURE";
